import React, { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
    Bot,
    Shield,
    Zap,
    Cpu,
    Coins,
    Lock,
    TrendingUp,
    RefreshCw,
    Activity,
    CheckCircle2,
    Sliders,
    ArrowUpRight,
    Terminal,
    Layers,
    Clock,
    Flame,
    PieChart,
    Wallet,
    AlertCircle,
    ChevronRight,
    Search
} from 'lucide-react'
import toast from 'react-hot-toast'

interface AIAgent {
    id: number
    name: string
    category: string
    riskScore: number
    fills: number
    successRate: number
    apy: number
    taoOracleStatus: string
    address: string
}

const initialAgents: AIAgent[] = []

export default function DeFAIPage(): React.JSX.Element {
    const [activeTab, setActiveTab] = useState<'simulator' | 'agents' | 'curation' | 'vortex' | 'mev'>('simulator')

    // Web3 / Canopy EVM Connection State
    const [connected, setConnected] = useState(false)
    const [walletAddress, setConnectedAddress] = useState<string | null>(null)
    const [rpcEndpoint] = useState('https://node1.canopy.us.nodefleet.net/v1/eth')
    const [chainId] = useState('0x1F2C (131072)')

    // AI Agents State
    const [agents, setAgents] = useState<AIAgent[]>(initialAgents)
    const [newAgentName, setNewAgentName] = useState('')
    const [newAgentCategory, setNewAgentCategory] = useState('Yield Arbitrage')

    // Yield Simulator & Smart Debt State
    const [collateralCnpy, setCollateralCnpy] = useState<number>(10000)
    const [borrowUsdc, setBorrowUsdc] = useState<number>(7000)
    const [isEmodeEnabled, setIsEmodeEnabled] = useState<boolean>(true)
    const [stakedEpShield, setStakedEpShield] = useState<number>(500)

    // veToken & Curation State
    const [lockAmount, setLockAmount] = useState<number>(1000)
    const [lockDurationDays, setLockDurationDays] = useState<number>(365) // 1 year

    // Intent Engine State
    const [intentText, setIntentText] = useState('')
    const [epGasBudget, setEpGasBudget] = useState(25)
    const [intentLogs, setIntentLogs] = useState<string[]>([])
    const [encryptedSwaps, setEncryptedSwaps] = useState<{ id: string; mevCaptured: number }[]>([])

    // Scarcity Vortex State
    const [totalSupplyEp] = useState<number>(21_000_000) // 21M cap
    const [totalBurnedEp, setTotalBurnedEp] = useState<number>(0)
    const hardFloorEp = 10_000_000
    const isHardFloorReached = totalSupplyEp - totalBurnedEp <= hardFloorEp

    // Calculated Yield Simulator Parameters
    const defaultLtv = 0.75
    const emodeLtv = 0.97
    const currentLtvLimit = isEmodeEnabled ? emodeLtv : defaultLtv
    const maxBorrowAllowed = collateralCnpy * currentLtvLimit
    const currentLtvRatio = collateralCnpy > 0 ? (borrowUsdc / collateralCnpy) : 0
    const healthFactor = borrowUsdc > 0 ? (collateralCnpy * (isEmodeEnabled ? 0.98 : 0.80)) / borrowUsdc : 99.9

    // Interest vs Yield Math
    const baseBorrowInterestRate = 0.05 // 5% APY
    const productiveAmmYieldRate = 0.085 // 8.5% APY generated by auto-routed borrowed capital
    const epShieldInterestOffsetRate = 0.06 // 6.0% interest offset from staked $EP

    const annualInterest = borrowUsdc * baseBorrowInterestRate
    const annualProductiveYield = borrowUsdc * productiveAmmYieldRate
    const annualEpShieldOffset = stakedEpShield * epShieldInterestOffsetRate
    const netAnnualRepayment = (annualProductiveYield + annualEpShieldOffset) - annualInterest

    // Multiplier calculation for veToken
    const getMultiplier = (days: number) => {
        if (days < 180) return 1.25
        if (days < 365) return 1.50
        if (days < 730) return 2.00
        if (days < 1460) return 2.50
        return 3.00
    }
    const currentMultiplier = getMultiplier(lockDurationDays)
    const calculatedVotingPower = lockAmount * currentMultiplier

    const handleConnectWallet = async () => {
        if (typeof window !== 'undefined' && (window as any).ethereum) {
            try {
                const accounts = await (window as any).ethereum.request({ method: 'eth_requestAccounts' })
                if (accounts && accounts.length > 0) {
                    setConnectedAddress(accounts[0])
                    setConnected(true)
                    toast.success('Connected to Canopy EVM via /v1/eth!')
                }
            } catch (err: any) {
                toast.error('Wallet connection rejected')
            }
        } else {
            toast.error('No Web3 wallet extension detected. Please install MetaMask orRabhy to connect to Canopy EVM.')
        }
    }

    const handleRegisterAgent = (e: React.FormEvent) => {
        e.preventDefault()
        if (!newAgentName.trim()) {
            toast.error('Please enter an Agent Name')
            return
        }
        const newAgent: AIAgent = {
            id: Date.now(),
            name: newAgentName,
            category: newAgentCategory,
            riskScore: Math.floor(Math.random() * 20) + 5,
            fills: 0,
            successRate: 100,
            apy: Number((Math.random() * 8 + 5).toFixed(1)),
            taoOracleStatus: 'Active - Zero Lag',
            address: `0x${Math.random().toString(16).substring(2, 6).toUpperCase()}...${Math.random().toString(16).substring(2, 6).toUpperCase()}`
        }
        setAgents((prev) => [newAgent, ...prev])
        setNewAgentName('')
        toast.success(`Registered Agent: ${newAgent.name}`)
    }

    const handleSubmitIntent = (e: React.FormEvent) => {
        e.preventDefault()
        if (!intentText.trim()) return
        const timestamp = new Date().toLocaleTimeString()
        const newLog = `[${timestamp}] Intent Executed: "${intentText}" | Gas Consumed: ${epGasBudget} $EP | Status: FILLED`
        const capturedMev = Number((Math.random() * 50 + 10).toFixed(2))
        
        setIntentLogs((prev) => [newLog, ...prev])
        setTotalBurnedEp((prev) => prev + epGasBudget)
        setEncryptedSwaps((prev) => [{ id: `Intent #${Math.floor(Math.random() * 90000 + 10000)}`, mevCaptured: capturedMev }, ...prev])
        toast.success('Intent filled with Zero Block Delay!')
        setIntentText('')
    }

    return (
        <div className="min-h-screen bg-[#0f0f0f] text-zinc-100 p-4 md:p-8 space-y-6">
            {/* Header Title & Canopy Network EVM Badge */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-zinc-800 pb-6">
                <div>
                    <div className="flex items-center gap-2">
                        <h1 className="text-2xl md:text-3xl font-bold tracking-tight text-white flex items-center gap-2">
                            <Cpu className="h-8 w-8 text-primary animate-pulse" />
                            DeFAI Nexus Protocol
                        </h1>
                        <span className="bg-primary/10 border border-primary/30 text-primary text-xs font-semibold px-2.5 py-0.5 rounded-full">
                            Canopy EVM Engine
                        </span>
                    </div>
                    <p className="text-zinc-400 text-sm mt-1">
                        Institutional DeFAI Engine, Smart Debt Vaults, E-Mode 97% LTV, and $EP Scarcity Vortex on Canopy Network.
                    </p>
                </div>

                {/* Web3 Canopy EVM Connection Controls */}
                <div className="flex flex-wrap items-center gap-3">
                    <div className="flex items-center gap-2 px-3 py-1.5 bg-[#171717] border border-zinc-800 rounded-xl text-xs">
                        <span className="h-2 w-2 rounded-full bg-emerald-500 animate-ping" />
                        <span className="text-zinc-400">Canopy EVM RPC:</span>
                        <span className="font-mono text-white text-[11px] truncate max-w-[140px]">{rpcEndpoint}</span>
                    </div>
                    <button
                        type="button"
                        onClick={handleConnectWallet}
                        className="flex items-center gap-2 px-4 py-2 bg-primary hover:bg-primary/90 text-black font-semibold rounded-xl text-sm transition-all"
                    >
                        <Wallet className="h-4 w-4" />
                        {connected ? `${walletAddress?.slice(0, 6)}...${walletAddress?.slice(-4)}` : 'Connect Wallet'}
                    </button>
                </div>
            </div>

            {/* Top Metrics Ticker */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="bg-[#171717] border border-zinc-800 rounded-xl p-4">
                    <div className="flex items-center justify-between text-xs text-zinc-400">
                        <span>Max E-Mode LTV</span>
                        <Zap className="h-4 w-4 text-amber-400" />
                    </div>
                    <div className="text-2xl font-bold text-white mt-1">97.00%</div>
                    <div className="text-[11px] text-emerald-400 mt-0.5">Correlated Stablecoin Category</div>
                </div>

                <div className="bg-[#171717] border border-zinc-800 rounded-xl p-4">
                    <div className="flex items-center justify-between text-xs text-zinc-400">
                        <span>$EP Total Supply</span>
                        <Coins className="h-4 w-4 text-primary" />
                    </div>
                    <div className="text-2xl font-bold text-white mt-1">21,000,000 $EP</div>
                    <div className="text-[11px] text-zinc-400 mt-0.5">
                        Burned: {(totalBurnedEp).toLocaleString()} $EP
                    </div>
                </div>

                <div className="bg-[#171717] border border-zinc-800 rounded-xl p-4">
                    <div className="flex items-center justify-between text-xs text-zinc-400">
                        <span>Scarcity Vortex Siphon</span>
                        <Flame className="h-4 w-4 text-rose-500" />
                    </div>
                    <div className="text-2xl font-bold text-white mt-1">40.0% Revenue</div>
                    <div className="text-[11px] text-rose-400 mt-0.5">
                        {isHardFloorReached ? 'Post-Floor: Real Yield Active' : 'Pre-Floor: Buyback & Burn'}
                    </div>
                </div>

                <div className="bg-[#171717] border border-zinc-800 rounded-xl p-4">
                    <div className="flex items-center justify-between text-xs text-zinc-400">
                        <span>Anti-MEV LP Vacuum</span>
                        <Shield className="h-4 w-4 text-sky-400" />
                    </div>
                    <div className="text-2xl font-bold text-white mt-1">100% MEV Captured</div>
                    <div className="text-[11px] text-sky-400 mt-0.5">Zero Mempool Leakage</div>
                </div>
            </div>

            {/* Navigation Tabs */}
            <div className="flex items-center gap-2 overflow-x-auto border-b border-zinc-800 pb-2">
                {[
                    { id: 'simulator', label: 'Smart Debt & Yield Simulator', icon: Sliders },
                    { id: 'agents', label: 'Autonomous AI Agents (Tier 3)', icon: Bot },
                    { id: 'curation', label: 'Social Curation & veToken (Tier 2)', icon: Lock },
                    { id: 'vortex', label: 'Scarcity Vortex & $EP Tokenomics', icon: Flame },
                    { id: 'mev', label: 'Anti-MEV LP Vacuum', icon: Shield },
                ].map((tab) => {
                    const Icon = tab.icon
                    const active = activeTab === tab.id
                    return (
                        <button
                            key={tab.id}
                            type="button"
                            onClick={() => setActiveTab(tab.id as any)}
                            className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium whitespace-nowrap transition-all ${
                                active
                                    ? 'bg-primary text-black font-semibold shadow-lg shadow-primary/20'
                                    : 'text-zinc-400 hover:bg-white/5 hover:text-white'
                            }`}
                        >
                            <Icon className="h-4 w-4" />
                            {tab.label}
                        </button>
                    )
                })}
            </div>

            {/* Tab 1: Yield Simulator & Smart Debt Vault */}
            {activeTab === 'simulator' && (
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    {/* Controls Panel */}
                    <div className="lg:col-span-1 bg-[#171717] border border-zinc-800 rounded-xl p-6 space-y-6">
                        <div className="flex items-center justify-between">
                            <h2 className="text-lg font-bold text-white flex items-center gap-2">
                                <Sliders className="h-5 w-5 text-primary" />
                                Smart Debt Controller
                            </h2>
                            <span className="text-xs bg-zinc-800 text-zinc-300 px-2 py-1 rounded-md">Live Config</span>
                        </div>

                        {/* E-Mode Toggle */}
                        <div className="bg-[#222] p-4 rounded-xl border border-zinc-800 space-y-3">
                            <div className="flex items-center justify-between">
                                <div>
                                    <div className="text-sm font-semibold text-white flex items-center gap-1.5">
                                        E-Mode (High-Efficiency)
                                        <Zap className="h-4 w-4 text-amber-400 fill-amber-400" />
                                    </div>
                                    <div className="text-xs text-zinc-400">Boosts LTV limit up to 97%</div>
                                </div>
                                <label className="relative inline-flex items-center cursor-pointer">
                                    <input
                                        type="checkbox"
                                        checked={isEmodeEnabled}
                                        onChange={(e) => setIsEmodeEnabled(e.target.checked)}
                                        className="sr-only peer"
                                    />
                                    <div className="w-11 h-6 bg-zinc-700 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-zinc-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary"></div>
                                </label>
                            </div>
                        </div>

                        {/* Collateral Input Slider */}
                        <div className="space-y-2">
                            <div className="flex justify-between text-sm">
                                <span className="text-zinc-400">Locked Collateral ($CNPY)</span>
                                <span className="font-mono text-primary font-bold">{collateralCnpy.toLocaleString()} CNPY</span>
                            </div>
                            <input
                                type="range"
                                min={1000}
                                max={100000}
                                step={1000}
                                value={collateralCnpy}
                                onChange={(e) => setCollateralCnpy(Number(e.target.value))}
                                className="w-full accent-primary bg-zinc-800 h-2 rounded-lg cursor-pointer"
                            />
                        </div>

                        {/* Borrow Amount Slider */}
                        <div className="space-y-2">
                            <div className="flex justify-between text-sm">
                                <span className="text-zinc-400">Borrowed Stablecoins (supUSDC)</span>
                                <span className="font-mono text-white font-bold">${borrowUsdc.toLocaleString()} USDC</span>
                            </div>
                            <input
                                type="range"
                                min={100}
                                max={maxBorrowAllowed}
                                step={100}
                                value={borrowUsdc}
                                onChange={(e) => setBorrowUsdc(Number(e.target.value))}
                                className="w-full accent-primary bg-zinc-800 h-2 rounded-lg cursor-pointer"
                            />
                            <div className="text-xs text-zinc-500 text-right">
                                Max Allowed ({ (currentLtvLimit * 100).toFixed(0) }% LTV): ${maxBorrowAllowed.toLocaleString()}
                            </div>
                        </div>

                        {/* Smart Debt Shield Staking */}
                        <div className="space-y-2">
                            <div className="flex justify-between text-sm">
                                <span className="text-zinc-400 flex items-center gap-1">
                                    <Shield className="h-3.5 w-3.5 text-sky-400" />
                                    Staked $EP Shield
                                </span>
                                <span className="font-mono text-sky-400 font-bold">{stakedEpShield.toLocaleString()} $EP</span>
                            </div>
                            <input
                                type="range"
                                min={0}
                                max={5000}
                                step={50}
                                value={stakedEpShield}
                                onChange={(e) => setStakedEpShield(Number(e.target.value))}
                                className="w-full accent-sky-400 bg-zinc-800 h-2 rounded-lg cursor-pointer"
                            />
                            <p className="text-[11px] text-zinc-500">
                                $EP staking yields continuously pay off loan interest to eliminate LTV creep.
                            </p>
                        </div>

                        <button
                            type="button"
                            onClick={() => toast.success('Smart Debt Position Updated on Canopy EVM!')}
                            className="w-full py-3 bg-primary text-black font-bold rounded-xl hover:bg-primary/90 transition-all text-sm"
                        >
                            Execute Smart Debt Strategy
                        </button>
                    </div>

                    {/* Simulation & Real-time Metrics Readout */}
                    <div className="lg:col-span-2 space-y-6">
                        <div className="bg-[#171717] border border-zinc-800 rounded-xl p-6 space-y-6">
                            <h2 className="text-lg font-bold text-white flex items-center gap-2">
                                <Activity className="h-5 w-5 text-primary" />
                                Real-Time Self-Repaying Loan Trajectory
                            </h2>

                            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                                <div className="bg-[#222] p-4 rounded-xl border border-zinc-800">
                                    <div className="text-xs text-zinc-400">Active LTV Ratio</div>
                                    <div className="text-2xl font-bold text-white mt-1">
                                        {(currentLtvRatio * 100).toFixed(1)}%
                                    </div>
                                    <div className="text-xs text-zinc-500 mt-1">
                                        Limit: {(currentLtvLimit * 100).toFixed(0)}%
                                    </div>
                                </div>

                                <div className="bg-[#222] p-4 rounded-xl border border-zinc-800">
                                    <div className="text-xs text-zinc-400">Health Factor</div>
                                    <div className={`text-2xl font-bold mt-1 ${healthFactor > 1.5 ? 'text-emerald-400' : 'text-amber-400'}`}>
                                        {healthFactor.toFixed(2)}
                                    </div>
                                    <div className="text-xs text-emerald-400 mt-1">Liquidation Safe</div>
                                </div>

                                <div className="bg-[#222] p-4 rounded-xl border border-zinc-800">
                                    <div className="text-xs text-zinc-400">Net Annual Pay-Down</div>
                                    <div className="text-2xl font-bold text-primary mt-1">
                                        +${netAnnualRepayment.toFixed(2)}/yr
                                    </div>
                                    <div className="text-xs text-primary mt-1">Self-Repaying Loan Active</div>
                                </div>
                            </div>

                            {/* Breakdown List */}
                            <div className="bg-[#222] p-4 rounded-xl border border-zinc-800 space-y-3">
                                <div className="text-xs font-semibold text-zinc-300 uppercase tracking-wider">
                                    Cash Flow & Interest Offset Breakdown
                                </div>
                                <div className="space-y-2 text-sm">
                                    <div className="flex justify-between">
                                        <span className="text-zinc-400">Borrow Interest Accrual (5.0% APY)</span>
                                        <span className="text-rose-400 font-mono">-${annualInterest.toFixed(2)} / yr</span>
                                    </div>
                                    <div className="flex justify-between">
                                        <span className="text-zinc-400">Productive AMM Yield (8.5% APY)</span>
                                        <span className="text-emerald-400 font-mono">+${annualProductiveYield.toFixed(2)} / yr</span>
                                    </div>
                                    <div className="flex justify-between">
                                        <span className="text-zinc-400">Smart Debt Shield Yield Offset (6.0%)</span>
                                        <span className="text-sky-400 font-mono">+${annualEpShieldOffset.toFixed(2)} / yr</span>
                                    </div>
                                    <div className="border-t border-zinc-700 pt-2 flex justify-between font-bold">
                                        <span className="text-white">Net Principal Reduction</span>
                                        <span className="text-primary font-mono">+${netAnnualRepayment.toFixed(2)} / yr</span>
                                    </div>
                                </div>
                            </div>

                            <div className="p-4 rounded-xl bg-primary/10 border border-primary/20 text-xs text-zinc-300 flex items-start gap-3">
                                <CheckCircle2 className="h-5 w-5 text-primary flex-shrink-0 mt-0.5" />
                                <div>
                                    <span className="font-semibold text-white">Productive Liability Confirmed: </span>
                                    Your borrowed USDC is not sitting idle. The AutoFi engine continuously routes funds into active AMM pools while your $EP Shield neutralizes interest, resulting in loan principal decay with zero manual rebalancing required.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Tab 2: Autonomous AI Agents & Intent Engine */}
            {activeTab === 'agents' && (
                <div className="space-y-6">
                    {/* Register Agent Form */}
                    <div className="bg-[#171717] border border-zinc-800 rounded-xl p-6">
                        <h3 className="text-base font-bold text-white flex items-center gap-2 mb-4">
                            <Bot className="h-5 w-5 text-primary" />
                            Register New Autonomous AI Agent
                        </h3>
                        <form onSubmit={handleRegisterAgent} className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                            <input
                                type="text"
                                value={newAgentName}
                                onChange={(e) => setNewAgentName(e.target.value)}
                                placeholder="Agent Name (e.g. Canopy Yield Optimizer)"
                                className="bg-[#222] border border-zinc-800 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-primary"
                            />
                            <select
                                value={newAgentCategory}
                                onChange={(e) => setNewAgentCategory(e.target.value)}
                                className="bg-[#222] border border-zinc-800 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-primary"
                            >
                                <option value="Yield Arbitrage">Yield Arbitrage</option>
                                <option value="Delta-Neutral AMM">Delta-Neutral AMM</option>
                                <option value="RWA Treasury">RWA Treasury</option>
                                <option value="Smart Debt Rebalancer">Smart Debt Rebalancer</option>
                            </select>
                            <button
                                type="submit"
                                className="py-2.5 bg-primary text-black font-bold rounded-xl hover:bg-primary/90 transition-all text-sm"
                            >
                                Register Agent
                            </button>
                        </form>
                    </div>

                    {agents.length === 0 ? (
                        <div className="bg-[#171717] border border-zinc-800 rounded-xl p-8 text-center text-zinc-400 space-y-2">
                            <Bot className="h-10 w-10 text-zinc-600 mx-auto" />
                            <p className="text-sm font-semibold text-white">No Active AI Agents Registered</p>
                            <p className="text-xs text-zinc-500">Register a custom AI agent above or dispatch an intent to execute automated strategies.</p>
                        </div>
                    ) : (
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                            {agents.map((agent) => (
                                <div key={agent.id} className="bg-[#171717] border border-zinc-800 rounded-xl p-5 space-y-4">
                                    <div className="flex items-start justify-between">
                                        <div>
                                            <div className="text-xs text-primary font-mono">{agent.category}</div>
                                            <h3 className="text-base font-bold text-white mt-1">{agent.name}</h3>
                                        </div>
                                        <span className="px-2 py-1 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-semibold rounded-lg">
                                            {agent.apy}% APY
                                        </span>
                                    </div>

                                    <div className="space-y-2 text-xs text-zinc-400">
                                        <div className="flex justify-between">
                                            <span>Risk Score (TAO Oracle):</span>
                                            <span className="text-white font-mono">{agent.riskScore} / 100</span>
                                        </div>
                                        <div className="flex justify-between">
                                            <span>Total Filled Intents:</span>
                                            <span className="text-white font-mono">{agent.fills}</span>
                                        </div>
                                        <div className="flex justify-between">
                                            <span>Execution Success Rate:</span>
                                            <span className="text-emerald-400 font-mono">{agent.successRate}%</span>
                                        </div>
                                        <div className="flex justify-between">
                                            <span>Agent Address:</span>
                                            <span className="text-zinc-300 font-mono">{agent.address}</span>
                                        </div>
                                    </div>

                                    <div className="pt-2 border-t border-zinc-800 flex items-center justify-between text-xs">
                                        <span className="text-zinc-500">{agent.taoOracleStatus}</span>
                                        <button
                                            type="button"
                                            onClick={() => toast.success(`Hired ${agent.name} for Meta-Vault!`)}
                                            className="px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-white rounded-lg transition-all"
                                        >
                                            Hire Agent
                                        </button>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}

                    {/* Intent Submission Portal & Live Execution Terminal */}
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                        <form onSubmit={handleSubmitIntent} className="bg-[#171717] border border-zinc-800 rounded-xl p-6 space-y-4">
                            <h3 className="text-lg font-bold text-white flex items-center gap-2">
                                <Zap className="h-5 w-5 text-primary" />
                                Submit User Intent (Tier 3 DeFAI)
                            </h3>

                            <div className="space-y-2">
                                <label className="text-xs text-zinc-400">Natural Language Intent / Constraint</label>
                                <input
                                    type="text"
                                    value={intentText}
                                    onChange={(e) => setIntentText(e.target.value)}
                                    placeholder='e.g. "Maintain 8% yield with <5% drawdown"'
                                    className="w-full bg-[#222] border border-zinc-800 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-primary"
                                />
                            </div>

                            <div className="space-y-2">
                                <label className="text-xs text-zinc-400">$EP Computational Gas Budget</label>
                                <input
                                    type="number"
                                    value={epGasBudget}
                                    onChange={(e) => setEpGasBudget(Number(e.target.value))}
                                    className="w-full bg-[#222] border border-zinc-800 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-primary"
                                />
                            </div>

                            <button
                                type="submit"
                                className="w-full py-3 bg-primary text-black font-bold rounded-xl hover:bg-primary/90 transition-all text-sm"
                            >
                                Dispatch Intent to AutoFi Solver
                            </button>
                        </form>

                        {/* Terminal Logs */}
                        <div className="bg-[#171717] border border-zinc-800 rounded-xl p-6 space-y-3 flex flex-col">
                            <h3 className="text-lg font-bold text-white flex items-center gap-2">
                                <Terminal className="h-5 w-5 text-sky-400" />
                                Intent Execution Logs (Zero Block Delay)
                            </h3>
                            <div className="flex-1 bg-black/80 border border-zinc-800 rounded-xl p-4 font-mono text-xs text-zinc-300 space-y-2 overflow-y-auto max-h-[220px]">
                                {intentLogs.length === 0 ? (
                                    <div className="text-zinc-600 italic">No intents executed in current session. Enter an intent on the left to dispatch.</div>
                                ) : (
                                    intentLogs.map((log, index) => (
                                        <div key={index} className="text-emerald-400/90 leading-relaxed">
                                            {log}
                                        </div>
                                    ))
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Tab 3: Social Curation & veToken Portal */}
            {activeTab === 'curation' && (
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                    <div className="bg-[#171717] border border-zinc-800 rounded-xl p-6 space-y-6">
                        <h2 className="text-lg font-bold text-white flex items-center gap-2">
                            <Lock className="h-5 w-5 text-primary" />
                            Lock $SUPRA / $EP to Mint veToken
                        </h2>

                        <div className="space-y-2">
                            <label className="text-xs text-zinc-400">Quantity to Lock</label>
                            <input
                                type="number"
                                value={lockAmount}
                                onChange={(e) => setLockAmount(Number(e.target.value))}
                                className="w-full bg-[#222] border border-zinc-800 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-primary"
                            />
                        </div>

                        {/* Lock Duration Selector */}
                        <div className="space-y-2">
                            <label className="text-xs text-zinc-400">Lock Duration</label>
                            <div className="grid grid-cols-5 gap-2">
                                {[
                                    { days: 90, label: '3 Mo', mult: '1.25x' },
                                    { days: 180, label: '6 Mo', mult: '1.50x' },
                                    { days: 365, label: '1 Yr', mult: '2.00x' },
                                    { days: 730, label: '2 Yr', mult: '2.50x' },
                                    { days: 1460, label: '4 Yr', mult: '3.00x' },
                                ].map((item) => (
                                    <button
                                        key={item.days}
                                        type="button"
                                        onClick={() => setLockDurationDays(item.days)}
                                        className={`py-2 px-1 text-center rounded-xl border text-xs font-semibold transition-all ${
                                            lockDurationDays === item.days
                                                ? 'bg-primary border-primary text-black'
                                                : 'bg-[#222] border-zinc-800 text-zinc-300 hover:border-zinc-700'
                                        }`}
                                    >
                                        <div>{item.label}</div>
                                        <div className="text-[10px] opacity-80">{item.mult}</div>
                                    </button>
                                ))}
                            </div>
                        </div>

                        <div className="bg-[#222] p-4 rounded-xl border border-zinc-800 space-y-2 text-sm">
                            <div className="flex justify-between">
                                <span className="text-zinc-400">Boost Multiplier:</span>
                                <span className="text-primary font-bold">{currentMultiplier.toFixed(2)}x</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-zinc-400">Minted Voting Power:</span>
                                <span className="text-white font-bold font-mono">{calculatedVotingPower.toLocaleString()} veEP</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-zinc-400">Soulbound Status:</span>
                                <span className="text-amber-400 text-xs">Locked (30-day anti-flash lock)</span>
                            </div>
                        </div>

                        <button
                            type="button"
                            onClick={() => toast.success(`Locked ${lockAmount} tokens for ${calculatedVotingPower} veEP!`)}
                            className="w-full py-3 bg-primary text-black font-bold rounded-xl hover:bg-primary/90 transition-all text-sm"
                        >
                            Create Vote-Escrow Lock
                        </button>
                    </div>

                    {/* Meta-Vault Social Curation */}
                    <div className="bg-[#171717] border border-zinc-800 rounded-xl p-6 space-y-6">
                        <h2 className="text-lg font-bold text-white flex items-center gap-2">
                            <TrendingUp className="h-5 w-5 text-primary" />
                            Curate Meta-Vaults & Earn 30% Bounties
                        </h2>

                        <p className="text-xs text-zinc-400 leading-relaxed">
                            Expert human curators use their locked veEP voting power to manage Meta-Vaults and strategically hire AI Agents. 30% of Agent-generated yield buys back $EP to reward curators.
                        </p>

                        <div className="space-y-4">
                            <div className="bg-[#222] p-4 rounded-xl border border-zinc-800 space-y-3">
                                <div className="flex justify-between items-center">
                                    <span className="font-bold text-white">Institutional RWA Meta-Vault #1</span>
                                    <span className="text-xs bg-primary/20 text-primary border border-primary/30 px-2 py-0.5 rounded-full">
                                        TVL: $12.4M
                                    </span>
                                </div>
                                <div className="text-xs text-zinc-400">
                                    Hired Agent: <span className="text-white font-semibold">Nexus-Alpha AI</span>
                                </div>
                                <div className="flex justify-between text-xs border-t border-zinc-800 pt-2">
                                    <span className="text-zinc-400">Curator EP Bounty Pool:</span>
                                    <span className="text-primary font-mono">+12,450 $EP</span>
                                </div>
                            </div>

                            <div className="bg-[#222] p-4 rounded-xl border border-zinc-800 space-y-3">
                                <div className="flex justify-between items-center">
                                    <span className="font-bold text-white">Delta-Neutral AMM Meta-Vault #2</span>
                                    <span className="text-xs bg-primary/20 text-primary border border-primary/30 px-2 py-0.5 rounded-full">
                                        TVL: $8.1M
                                    </span>
                                </div>
                                <div className="text-xs text-zinc-400">
                                    Hired Agent: <span className="text-white font-semibold">Quant-Garch Agent</span>
                                </div>
                                <div className="flex justify-between text-xs border-t border-zinc-800 pt-2">
                                    <span className="text-zinc-400">Curator EP Bounty Pool:</span>
                                    <span className="text-primary font-mono">+8,920 $EP</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Tab 4: Scarcity Vortex & $EP Tokenomics */}
            {activeTab === 'vortex' && (
                <div className="bg-[#171717] border border-zinc-800 rounded-xl p-6 space-y-6">
                    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-zinc-800 pb-4">
                        <div>
                            <h2 className="text-lg font-bold text-white flex items-center gap-2">
                                <Flame className="h-5 w-5 text-rose-500" />
                                The Scarcity Vortex (21 Million Max Supply)
                            </h2>
                            <p className="text-xs text-zinc-400 mt-1">
                                40% of protocol revenues automatically buy back and burn $EP until hitting the Hard Floor, where it converts into Real Yield dividends.
                            </p>
                        </div>
                        <div className="text-right">
                            <span className="text-xs text-zinc-400">Floor Status:</span>
                            <div className="text-sm font-bold text-emerald-400">
                                {isHardFloorReached ? 'Hard Floor Reached (Real Yield Mode)' : 'Pre-Floor State (Deflationary Siphon)'}
                            </div>
                        </div>
                    </div>

                    {/* Progress Bar towards Hard Floor */}
                    <div className="space-y-2">
                        <div className="flex justify-between text-xs">
                            <span className="text-zinc-400">Circulating Supply: {(totalSupplyEp - totalBurnedEp).toLocaleString()} $EP</span>
                            <span className="text-zinc-400">Hard Floor: 10,000,000 $EP</span>
                        </div>
                        <div className="w-full bg-zinc-800 h-4 rounded-full overflow-hidden p-0.5 border border-zinc-700">
                            <div
                                className="bg-gradient-to-r from-rose-500 to-amber-500 h-full rounded-full transition-all duration-500"
                                style={{ width: `${Math.min(100, (totalBurnedEp / (21_000_000 - hardFloorEp)) * 100)}%` }}
                            ></div>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <div className="bg-[#222] p-4 rounded-xl border border-zinc-800 space-y-1">
                            <div className="text-xs text-zinc-400">Founder Allocation (1%)</div>
                            <div className="text-lg font-bold text-white font-mono">210,000 $EP</div>
                            <div className="text-xs text-zinc-500">1-Year Non-Custodial Linear Vesting</div>
                        </div>

                        <div className="bg-[#222] p-4 rounded-xl border border-zinc-800 space-y-1">
                            <div className="text-xs text-zinc-400">Total $EP Burned</div>
                            <div className="text-lg font-bold text-rose-400 font-mono">{totalBurnedEp.toLocaleString()} $EP</div>
                            <div className="text-xs text-zinc-500">Siphoned via 40% AI Performance Fees</div>
                        </div>

                        <div className="bg-[#222] p-4 rounded-xl border border-zinc-800 space-y-1">
                            <div className="text-xs text-zinc-400">30% Curation Bounties</div>
                            <div className="text-lg font-bold text-primary font-mono">+48,290 USDC</div>
                            <div className="text-xs text-zinc-500">Distributed to Active Curators</div>
                        </div>
                    </div>
                </div>
            )}

            {/* Tab 5: Anti-MEV LP Vacuum */}
            {activeTab === 'mev' && (
                <div className="bg-[#171717] border border-zinc-800 rounded-xl p-6 space-y-6">
                    <div className="flex items-center justify-between border-b border-zinc-800 pb-4">
                        <div>
                            <h2 className="text-lg font-bold text-white flex items-center gap-2">
                                <Shield className="h-5 w-5 text-sky-400" />
                                Anti-MEV LP Vacuum (Encrypted Intent Routing)
                            </h2>
                            <p className="text-xs text-zinc-400 mt-1">
                                Captures 100% of internal arbitrage and sandwich value, directing it back into the protocol reserve instead of public searchers.
                            </p>
                        </div>
                        <span className="px-3 py-1 bg-sky-500/10 border border-sky-500/20 text-sky-400 text-xs font-semibold rounded-lg">
                            Encrypted Routing Active
                        </span>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div className="bg-[#222] p-5 rounded-xl border border-zinc-800 space-y-4">
                            <h3 className="text-sm font-bold text-white">Internal MEV Capture Statistics</h3>
                            <div className="space-y-3 text-xs">
                                <div className="flex justify-between">
                                    <span className="text-zinc-400">Captured Arbitrage Value:</span>
                                    <span className="text-emerald-400 font-mono font-bold">$184,290 USDC</span>
                                </div>
                                <div className="flex justify-between">
                                    <span className="text-zinc-400">Mempool Leakage Prevented:</span>
                                    <span className="text-white font-mono">100.0%</span>
                                </div>
                                <div className="flex justify-between">
                                    <span className="text-zinc-400">Encrypted Intent Batches Processed:</span>
                                    <span className="text-white font-mono">14,290</span>
                                </div>
                            </div>
                        </div>

                        <div className="bg-[#222] p-5 rounded-xl border border-zinc-800 space-y-3">
                            <h3 className="text-sm font-bold text-white">Recent Encrypted Swaps</h3>
                            <div className="font-mono text-xs space-y-2 text-zinc-400">
                                {encryptedSwaps.length === 0 ? (
                                    <div className="text-zinc-600 italic">No encrypted swaps recorded yet. Dispatch an intent in the AI Agents tab to simulate Anti-MEV routing.</div>
                                ) : (
                                    encryptedSwaps.map((swap, idx) => (
                                        <div key={idx} className="flex justify-between border-b border-zinc-800 pb-1">
                                            <span>{swap.id}</span>
                                            <span className="text-emerald-400">Captured ${swap.mevCaptured.toFixed(2)} MEV</span>
                                        </div>
                                    ))
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    )
}
